"""empty message

Revision ID: 33e5799a0e25
Revises: 9b8cf67a0b81
Create Date: 2025-07-09 16:53:41.899588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e5799a0e25'
down_revision = '9b8cf67a0b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
