"""empty message

Revision ID: 984b1a2dde40
Revises: 
Create Date: 2025-07-05 01:28:35.833938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984b1a2dde40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('products2_pkey'))
    )
    # ### end Alembic commands ###
